version: '3.8'

services:
  geo-service:
    build: ./python-microservice
    ports:
      - "8000:8000"
    networks:
      - geo-network

  nestjs-api:
    build: ./nestjs-api
    ports:
      - "3001:3001"
    networks:
      - geo-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - geo-network
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  geo-network:
    driver: bridge